### ISSUE TITLE
Switch to NixOS foundation account and go live

### ISSUE THREAD

**Issue by arianvp** [NixOS/amis#78]

**Comment by greed42** [comment]
I hate to ask, but as the NixOS foundation images are gone... do you have an estimate for the go-live?

I'm basing "gone" on both API and Web queries for images with owner `080433136561`. Also just searching for public images matching `NixOS-23.05.*` turns up nothing, which are the ones we'd been using (and channel-switching to 23.11) up until now.

https://eu-west-1.console.aws.amazon.com/ec2/home?region=eu-west-1#Images:visibility=public-images;owner=080433136561;v=3;$case=tags:false%5C,client:false;$regex=tags:false%5C,client:false

**Comment by arianvp** [comment]
Of timelines launching this for 23.11 and 24.05.  My hope is to have migrated to the new account this week. (Note that this will be a new account separate from `080433136561` ).

**Comment by arianvp** [comment]
Do you mean that the images here disappeared?:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/amazon-ec2-amis.nix

**Comment by arianvp** [comment]
```
 aws ec2 describe-images --region eu-west-2  --owner 080433136561
```

also works for me. All the images are there.

**Comment by greed42** [comment]
Oh I didn't think of trying a different region!

```
aws ec2 describe-images --region eu-west-1  --owner 080433136561
{
    "Images": []
}
```

But yes, I can see them in eu-west-2. They absolutely used to be in eu-west-1 as well.

```
aws ec2 describe-images --region eu-west-2  --owner 080433136561 | jq 'reduce .Images[] as $item (0; . + 1)'
9
```

This is obviously the wrong ticket for this -- do you have a suggestion for an appropriate reporting channel?

**Comment by arianvp** [comment]
Seems maybe somebody might have accidentally removed images in some of the regions. This is the reason why we are  moving  AMIs to a dedicated account in the first place. I hope this won't happen again with the new upload process I developed in this repo.
 I'll check in  the #infra:nixos.org channel on Matrix to see what happened.

**Comment by arianvp** [comment]
Cleared up with the infra team. Seems during the cleanup of snapshots in `eu-west-1` these were accidentally deleted. I'm sorry.

I'll make  sure to upload the 23.11 image to eu-west-1 too

**Comment by greed42** [comment]
Ah; thanks for the info.

Your experimental images are working fine in eu-west-1 so far.

**Comment by arianvp** [comment]
Done
