### ISSUE TITLE
include ssm-agent by default in the image

### ISSUE THREAD

**Issue by pokgak** [NixOS/amis#92]
Will this new AMI include ssm-agent package by default? I see from the files in this repo that you're currently including the newer EC2 Instance Connect but nothing on ssm-agent. Will there be a choice to choose which one?

I'm coming from this issue: https://github.com/NixOS/nixpkgs/issues/222637

**Comment by arianvp** [comment]
So for initial release I am just uploading the existing  image  build from Hydra as is.  This will neither contain SSM-agent nor EC2 Instance Connect.

The NixOS configurations in this repo are _NOT_ being used by the upload process yet  at the moment.  I'll try to make this clear in the README as it's a bit confusing.

However I am planning to move to the image builder in this repo and I want to have  both EIC and ssm-agent support.

**Comment by pokgak** [comment]
noted. thank you for the reply.

**Comment by arianvp** [comment]
The 24.05 AMIs contain ssm-agent
